wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1675937158.468309
    t:
      1:
      - 1
      - 55
      - 79
      2:
      - 1
      - 55
      - 79
      3:
      - 23
      4: 3.10.6
      5: 0.13.10
      8:
      - 3
      - 5
